# This workflow will render the README stats from the url list.

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'  # Run at midnight UTC every day
  workflow_dispatch:  # Allow manual triggering    

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to push changes

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    
    - name: Render README
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python make.py -t $GH_TOKEN
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md repos.json
        if ! git diff --quiet --staged; then
          git commit -m "Update README and repository data"
          git push
        fi
